export * from '@doars/staark-common/src/conditional.js'
export * from '@doars/staark-common/src/factory.js'
export * from '@doars/staark-common/src/fctory.js'
export * from '@doars/staark-common/src/match.js'
export * from '@doars/staark-common/src/nde.js'
export * from '@doars/staark-common/src/node.js'
export * from '@doars/staark-common/src/text.js'
export * from './library/patch.js'
